//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fruit
    {
        public int FruitId { get; set; }
        public string FruitName { get; set; }
        public string Color { get; set; }
        public Nullable<int> Preference { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string FruitImage { get; set; }
    }
}
