//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblcity> tblcities { get; set; }
        public virtual DbSet<tblcountry> tblcountries { get; set; }
        public virtual DbSet<tblstate> tblstates { get; set; }
        public virtual DbSet<Fruit> Fruits { get; set; }
        public virtual DbSet<ApplicationLog> ApplicationLogs { get; set; }
    }
}
