//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcountry
    {
        public Nullable<int> id { get; set; }
        public string shortname { get; set; }
        public string countryname { get; set; }
        public int phonecode { get; set; }
    }
}
